version: 0.2

#$CODEBUILD_SRC_DIR is is a given env var
#$CognitoUserPoolId is is a given env var
#$CognitoUserPoolArn is is a given env var
#$CognitoClientId is is a given env var

env:
  variables:
    BUILD_ENV: "prod"
phases:
  install:
    commands:
      - echo "Upgrading NPM"
      - npm install -g npm
      - echo "Changing to Source Directory"
      - cd src
      - echo "Installing NPM dependencies"
      - npm install #--unsafe-perm
      - echo "Installing Angular CLI"
      - npm install -g --unsafe-perm @angular/cli@latest
  pre_build:
    commands:
      - echo "pre-build commands..."
      - "[[ -d ../src ]] || echo 'Missing src dir'"
      - "[[ -d ../scaffolding ]] || echo 'Missing scaffolding dir'"
      - "[[ -d ../package ]] || echo 'Missing package dir'"
      - "echo \"
        export const environment = {
        production: false,
        region: us-east-1,
        identityPoolId: not_used_right_now,
        userPoolId: ${CognitoUserPoolId},
        clientId: ${CognitoClientId}};\" > ../src/src/environments/environment.ts"

  build:
    commands:
      - echo "build command..."
      - ng build --env=${BUILD_ENV}
  post_build:
    commands:
      - cd ..
      - mkdir ./package/swagger-ui
      - cp -r ./src/src/swagger-ui/* ./package/swagger-ui/
     # - sed  -n '/BEGIN SWAGGER/,/END SWAGGER/{/END SWAGGER/!p}' ./scaffolding/transforms/swagger_v2.yml > ./package/swagger-ui/swagger.yml
     # - export s='!Ref CognitoId'
     # - "export r=$(aws cognito-idp list-user-pools --max-results=1 | grep Id | sed 's#\"Id\": \".##' | sed 's#\",.##')"
     # - sed -i "s/$s/$r/g" *
      - cp -r ./src/dist/* ./package/
      - cp -r ./scaffolding/* ./package/
artifacts:
  files:
    - ./package/**/*
